name: Simple Workflow

on: 
  push :

  workflow_dispatch: 
    inputs:
      CONFIGUREATION:
        description: '構成の選択'
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
    
jobs:
  Example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # 自作アクションと定義済みアクションテスト
      - uses: ./.github/actions/sample
      # 変数を使用する
      - uses: ./.github/actions/useEnvJob
        with:
          witch: "魔法使いです"   
