name: Simple Workflow

on: 
  push :

  workflow_dispatch: 
    inputs:
      CONFIGUREATION:
        description: '構成の選択'
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release

env:
    DRAGON: I'm Dragon
    
jobs:
  # 自作アクションと定義済みアクションテスト
  CreateActionJob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sample

  # 変数を使用する
  UseEnvJob:
    runs-on: ubuntu-latest
    
    env:
      OGRE: I'm Ogre

    steps:
      - name: Who are you? 
        env:
          WITCH: I'm Witch
        run: |
          echo "DRAGON=$DRAGON"
          echo "OGRE = ${{ env.OGRE }}"
          echo "WITCH=$WITCH"
